//! Configuration setup for init command

use std::{fs, path::Path};

use anyhow::{Context, Result};

/// Default configuration content from config.cue
const DEFAULT_CONFIG: &str = r#"# zjj Configuration File
# This file was generated by 'zjj init'

workspace_dir = "../{repo}__workspaces"
# main_branch = "main"  # Optional: set to auto-detect (default) or specify branch name
default_template = "standard"
state_db = ".zjj/state.db"

[watch]
enabled = true
debounce_ms = 100
paths = [".beads/beads.db"]

[hooks]
post_create = []
pre_remove = []
post_merge = []

[zellij]
session_prefix = "zjj"
use_tabs = true
layout_dir = ".zjj/layouts"

[zellij.panes.main]
command = "claude"
args = []
size = "70%"

[zellij.panes.beads]
command = "bv"
args = []
size = "50%"

[zellij.panes.status]
command = "zjj"
args = ["status", "--watch"]
size = "50%"

[zellij.panes.float]
enabled = true
command = ""
width = "80%"
height = "60%"

[dashboard]
refresh_ms = 1000
theme = "default"
columns = ["name", "status", "branch", "changes", "beads"]
vim_keys = true

[agent]
command = "claude"

[agent.env]

[session]
auto_commit = false
commit_prefix = "wip:"
"#;

/// Setup configuration files in the .zjj directory
///
/// Creates:
/// - config.toml with default configuration
/// - layouts/ directory for Zellij layouts
///
/// # Errors
///
/// Returns error if:
/// - Cannot write config.toml file
/// - Cannot create layouts directory
/// - Insufficient permissions
pub fn setup_config(zjj_dir: &Path) -> Result<()> {
    // Create config.toml with defaults
    let config_path = zjj_dir.join("config.toml");
    fs::write(&config_path, DEFAULT_CONFIG)
        .context("Failed to create config.toml")
        .context("Suggestions:")
        .context(format!(
            "  - Check write permissions for: {}",
            config_path.display()
        ))
        .context("  - Ensure the .zjj directory was created successfully")
        .context("  - Check disk space: df -h")?;

    // Create layouts directory
    let layouts_dir = zjj_dir.join("layouts");
    fs::create_dir_all(&layouts_dir)
        .context("Failed to create layouts directory")
        .context("Suggestions:")
        .context(format!(
            "  - Check write permissions in: {}",
            zjj_dir.display()
        ))
        .context("  - Ensure the .zjj directory exists and is writable")?;

    Ok(())
}

/// Get the default configuration content
///
/// This is exposed for testing purposes to verify the default config is valid TOML
#[allow(dead_code)]
#[must_use]
pub const fn default_config() -> &'static str {
    DEFAULT_CONFIG
}

#[cfg(test)]
mod tests {
    use tempfile::TempDir;

    use super::*;

    #[test]
    fn test_setup_config_creates_config_toml() -> Result<()> {
        let temp_dir = TempDir::new()?;
        let zjj_dir = temp_dir.path().join(".zjj");
        fs::create_dir_all(&zjj_dir)?;

        setup_config(&zjj_dir)?;

        let config_path = zjj_dir.join("config.toml");
        assert!(config_path.exists(), "config.toml should be created");
        assert!(config_path.is_file(), "config.toml should be a file");

        let content = fs::read_to_string(&config_path)?;
        assert!(content.contains("workspace_dir"));
        assert!(content.contains("[watch]"));
        assert!(content.contains("[zellij]"));
        assert!(content.contains("[dashboard]"));

        Ok(())
    }

    #[test]
    fn test_setup_config_creates_layouts_directory() -> Result<()> {
        let temp_dir = TempDir::new()?;
        let zjj_dir = temp_dir.path().join(".zjj");
        fs::create_dir_all(&zjj_dir)?;

        setup_config(&zjj_dir)?;

        let layouts_dir = zjj_dir.join("layouts");
        assert!(layouts_dir.exists(), "layouts directory should be created");
        assert!(layouts_dir.is_dir(), "layouts should be a directory");

        Ok(())
    }

    #[test]
    fn test_default_config_is_valid_toml() -> Result<()> {
        let parsed: toml::Value =
            toml::from_str(DEFAULT_CONFIG).context("DEFAULT_CONFIG is not valid TOML")?;

        assert!(parsed.get("watch").is_some());
        assert!(parsed.get("zellij").is_some());
        assert!(parsed.get("dashboard").is_some());
        assert!(parsed.get("agent").is_some());
        assert!(parsed.get("session").is_some());

        Ok(())
    }

    #[test]
    fn test_default_config_has_correct_values() -> Result<()> {
        let parsed: toml::Value = toml::from_str(DEFAULT_CONFIG)?;

        assert_eq!(
            parsed.get("workspace_dir").and_then(|v| v.as_str()),
            Some("../{repo}__workspaces")
        );
        assert_eq!(
            parsed.get("default_template").and_then(|v| v.as_str()),
            Some("standard")
        );

        let watch = parsed.get("watch").and_then(|v| v.as_table());
        assert!(watch.is_some());
        assert_eq!(
            watch
                .and_then(|w| w.get("enabled"))
                .and_then(toml::Value::as_bool),
            Some(true)
        );
        assert_eq!(
            watch
                .and_then(|w| w.get("debounce_ms"))
                .and_then(toml::Value::as_integer),
            Some(100)
        );

        let zellij = parsed.get("zellij").and_then(|v| v.as_table());
        assert!(zellij.is_some());
        assert_eq!(
            zellij
                .and_then(|z| z.get("session_prefix"))
                .and_then(|v| v.as_str()),
            Some("zjj")
        );
        assert_eq!(
            zellij
                .and_then(|z| z.get("use_tabs"))
                .and_then(toml::Value::as_bool),
            Some(true)
        );

        Ok(())
    }
}
